const o = (id, label, tags = {}) => ({ id, label, tags });

export const phaseOrder = [
  "onboarding",
  "identity",
  "identity_checkpoint",
  "joy_flow",
  "joy_flow_checkpoint",
  "talents",
  "emotions",
  "emotions_checkpoint",
  "work_style",
  "work_style_checkpoint",
  "business",
  "profile_synthesis",
  "suggested_paths",
  "seven_day_experiment",
  "decision_system",
  "final_report",
];

export const phases = {
  onboarding: {
    id: "onboarding",
    order: 0,
    eyebrow: "Etap 0",
    title: "Onboarding",
    subtitle:
      "To nie jest test ani diagnoza. To spokojny proces wracania do siebie, porzadkowania sygnalow i szukania kierunku, ktory mozesz potem lagodnie sprawdzic w praktyce.",
    questions: [
      {
        id: "onboarding_info",
        type: "info",
        title: "Zanim zaczniemy",
        description:
          "Nie szukamy jednej idealnej odpowiedzi. Szukamy powtarzajacych sie wzorcow: co Cie przyciaga, co daje Ci energie, co Cie porusza i jaki styl dzialania jest z Toba zgodny.",
      },
      {
        id: "onboarding_support",
        type: "info",
        title: "To normalne, jesli nie masz jasnosci",
        description:
          "Mozesz odpowiadac fragmentami, chaotycznie albo niepewnie. Brak gotowej odpowiedzi tez jest informacja. Ten proces nie zastepuje terapii ani profesjonalnego wsparcia psychologicznego - mozesz zatrzymac sie, pominac pytanie albo wrocic pozniej.",
      },
      {
        id: "onboarding_needs",
        type: "multi",
        title: "Z czym najbardziej przychodzisz?",
        options: [
          o("discover_likes", "Chce odkryc, co naprawde lubie", { meaning: 1, explorer: 1 }),
          o("stuck", "Czuje, ze stoje w miejscu", { meaning: 1 }),
          o("business_idea", "Chce znalezc pomysl na biznes", { businessReadiness: 2, freedom: 1 }),
          o("talents", "Chce lepiej poznac swoje talenty", { explorer: 1 }),
          o("daily_meaning", "Chce poczuc wiecej sensu na co dzien", { meaning: 2 }),
          o("too_many_ideas", "Mam duzo pomyslow, ale nie wiem, ktory wybrac", { creative: 1, explorer: 1 }),
          o("orientation", "Nie wiem jeszcze - chce sie rozeznac", { explorer: 2 }),
        ],
      },
      {
        id: "expected_result",
        type: "single",
        title: "Co byloby dla Ciebie wartosciowym wynikiem?",
        options: [
          o("self_understanding", "Lepsze zrozumienie siebie", { explorer: 1, meaning: 1 }),
          o("career_ideas", "Konkretne pomysly na kierunek zawodowy", { strategic: 1 }),
          o("project_business", "Pomysl na biznes lub projekt", { businessReadiness: 2 }),
          o("experiments", "Plan malych eksperymentow", { builder: 1, strategic: 1 }),
          o("all", "Polaczenie wszystkiego powyzej", { explorer: 1, strategic: 1, businessReadiness: 1 }),
        ],
      },
      {
        id: "honesty_contract",
        type: "checkbox",
        title: "Rozumiem, ze nie musze odpowiadac idealnie",
        description:
          "Ten proces dziala najlepiej, gdy odpowiadasz szczerze, nie ladnie. Mozesz pisac chaotycznie, krotko albo emocjonalnie.",
        checkboxLabel: "Rozumiem i chce odpowiadac szczerze",
        required: true,
      },
    ],
  },
  identity: {
    id: "identity",
    order: 1,
    eyebrow: "Etap 1",
    title: "Naturalna tozsamosc",
    subtitle:
      "Ten etap pomaga zobaczyc, co pojawia sie naturalnie, zanim wlacza sie oczekiwania, rozsadek albo porownywanie sie z innymi. Nie musisz niczego udowadniac - wystarczy, ze zbierzesz slady.",
    questions: [
      {
        id: "identity_support",
        type: "info",
        title: "To normalne, jesli czujesz opor",
        description:
          "Przy pytaniach o siebie czesto pojawia sie pustka, opor albo mysli typu nie wiem. Nie walcz z tym. Zapisz tyle, ile jest dzisiaj dostepne.",
      },
      {
        id: "free_day",
        type: "textarea",
        title: "Masz caly dzien tylko dla siebie",
        description:
          "Wyobraz sobie dzien, w ktorym nikt Cie nie ocenia, nikt niczego od Ciebie nie oczekuje i nie musisz byc produktywna. Co naturalnie robisz przez pierwsze 3 godziny?",
        placeholder:
          "Opisz konkretnie: co robisz, gdzie jestes, czy jestes sama, czy z kims, co sprawia Ci przyjemnosc...",
      },
      {
        id: "most_yourself_moment",
        type: "textarea",
        title: "Kiedy czujesz sie najbardziej soba?",
        description:
          "Przypomnij sobie moment z ostatnich miesiecy, w ktorym poczulas: to jestem naprawde ja. Co sie wtedy dzialo?",
      },
      {
        id: "childhood_patterns",
        type: "textarea",
        title: "Co robilas naturalnie jako dziecko albo nastolatka?",
        description:
          "Zanim zaczelas myslec o tym, co wypada, co sie oplaca albo co inni uznaja za rozsadne - co Cie wciagalo?",
        placeholder:
          "Rysowanie, pisanie, organizowanie zabaw, opiekowanie sie kims, wystepowanie, dekorowanie, sport, rozmowy, pomaganie, wymyslanie historii...",
      },
      {
        id: "natural_easy_things",
        type: "multi",
        title: "Co przychodzi Ci wzglednie latwo?",
        options: [
          o("emotions", "Wyczuwanie emocji innych ludzi", { relational: 2, caring: 2 }),
          o("facts", "Laczenie faktow", { analytical: 2, strategic: 1 }),
          o("ideas", "Wymyslanie pomyslow", { creative: 2, explorer: 1 }),
          o("aesthetic", "Tworzenie estetycznych rzeczy", { aesthetic: 2, creative: 1 }),
          o("explain", "Tlumaczenie czegos prostym jezykiem", { educational: 2, communication: 2 }),
          o("organize", "Organizowanie chaosu", { organizational: 2, strategic: 1 }),
          o("motivate", "Motywowanie innych", { leadership: 2, communication: 1 }),
          o("listen", "Sluchanie ludzi", { relational: 2, caring: 1 }),
          o("learn", "Szybkie uczenie sie", { explorer: 2, analytical: 1 }),
          o("details", "Zauwazanie detali", { analytical: 1, aesthetic: 1 }),
          o("atmosphere", "Budowanie atmosfery", { relational: 1, aesthetic: 1, caring: 1 }),
          o("writing", "Pisanie", { communication: 2, creative: 1 }),
          o("speaking", "Mowienie", { communication: 2, visibility: 1 }),
          o("planning", "Planowanie", { strategic: 2, organizational: 1 }),
          o("solving", "Rozwiazywanie problemow", { analytical: 2, strategic: 1 }),
        ],
      },
      {
        id: "endless_topics",
        type: "textarea",
        title: "O jakich tematach mozesz rozmawiac albo myslec dlugo?",
        description:
          "Chodzi o tematy, ktore nie mecza Cie od razu, tylko naturalnie Cie przyciagaja.",
      },
      {
        id: "identity_self_check",
        type: "single",
        title: "Na tym etapie szukamy Twojej naturalnosci. Co czujesz po tych pytaniach?",
        options: [
          o("clarity", "Mam wieksza jasnosc", { meaning: 1 }),
          o("forming", "Cos sie zaczyna ukladac", { explorer: 1 }),
          o("traces", "Dalej nie wiem, ale widze kilka sladow", { explorer: 1 }),
          o("resistance", "Mam opor albo trudno mi odpowiedziec"),
        ],
      },
    ],
  },
  identity_checkpoint: {
    id: "identity_checkpoint",
    order: 2,
    eyebrow: "Checkpoint 1",
    title: "Sygnal z tego etapu",
    subtitle:
      "Nie potrzebujesz jeszcze wnioskow na cale zycie. Zatrzymaj sie na chwile i zobacz, co po etapie o naturalnej tozsamosci zaczyna sie delikatnie wybijac.",
    generated: "checkpoint",
    checkpointFor: "identity",
    questions: [
      {
        id: "identity_checkpoint_note",
        type: "textarea",
        title: "Jedna mysl na dzis",
        description: "Zapisz jedna mysl, ktora chcesz ze soba zabrac po tym etapie.",
        placeholder: "Np. coraz wyrazniej widze..., zaskoczylo mnie..., chce dalej obserwowac...",
        required: false,
        trackProgress: false,
      },
    ],
  },
  joy_flow: {
    id: "joy_flow",
    order: 3,
    eyebrow: "Etap 2",
    title: "Radosc, energia i flow",
    subtitle:
      "Nie wszystko, co lubimy, powinno stac sie praca. Na razie sprawdzamy tylko, co Cie ozywia, a co odcina Cie od siebie.",
    questions: [
      {
        id: "energizing_activities",
        type: "multi",
        title: "Po ktorych aktywnosciach czujesz sie bardziej zywa?",
        options: [
          o("create_from_zero", "Tworzenie czegos od zera", { creative: 2, builder: 1 }),
          o("deep_1_1", "Gleboka rozmowa 1:1", { relational: 2, caring: 1 }),
          o("help_problem", "Pomaganie komus rozwiazac problem", { caring: 2, strategic: 1 }),
          o("learn_new", "Uczenie sie czegos nowego", { explorer: 2, analytical: 1 }),
          o("share_knowledge", "Dzielenie sie wiedza", { educational: 2, communication: 1 }),
          o("design_aesthetic", "Projektowanie czegos estetycznego", { aesthetic: 2, creative: 1 }),
          o("organize_space", "Organizowanie przestrzeni lub procesu", { organizational: 2, builder: 1 }),
          o("visible", "Wystepowanie lub bycie widziana", { visibility: 2, communication: 1 }),
          o("quiet_focus", "Praca w ciszy i skupieniu", { independent: 2, analytical: 1 }),
          o("body_nature", "Ruch, cialo albo natura", { meaning: 1 }),
          o("lead_people", "Prowadzenie ludzi", { leadership: 2, communication: 1 }),
          o("strategy", "Wymyslanie strategii", { strategic: 2, analytical: 1 }),
          o("people_analysis", "Analizowanie zachowan ludzi", { analytical: 1, relational: 1 }),
          o("content", "Tworzenie tresci", { creative: 2, communication: 2 }),
          o("sales_value", "Sprzedaz albo rozmowy o wartosci", { businessReadiness: 2, communication: 1 }),
        ],
      },
      {
        id: "last_flow_moment",
        type: "textarea",
        title: "Kiedy ostatnio stracilas poczucie czasu?",
        description:
          "Opisz sytuacje, w ktorej tak sie w cos wciagnelas, ze czas minal szybciej niz zwykle.",
      },
      {
        id: "draining_activities",
        type: "multi",
        title: "Co najczesciej odbiera Ci energie?",
        options: [
          o("chaos", "Chaos i brak planu", { organizational: 1 }),
          o("too_much_structure", "Nadmiar struktury i kontroli", { freedom: 2 }),
          o("too_many_people", "Zbyt duzo kontaktu z ludzmi", { independent: 1 }),
          o("too_alone", "Zbyt duzo samotnej pracy", { relational: 1 }),
          o("repetition", "Powtarzalne zadania", { creative: 1, explorer: 1 }),
          o("visibility_pressure", "Presja widocznosci", { visibility: -2 }),
          o("sales", "Sprzedaz", { businessReadiness: -1 }),
          o("conflict", "Konflikt"),
          o("no_meaning", "Brak sensu", { meaning: 2 }),
          o("no_effects", "Brak efektow", { builder: 1 }),
          o("criticism", "Krytyka", { visibility: -1 }),
          o("fast_pace", "Szybkie tempo", { stability: 1 }),
          o("monotony", "Monotonia", { explorer: 1 }),
          o("pretending", "Koniecznosc udawania kogos innego", { meaning: 2, freedom: 1 }),
        ],
      },
      {
        id: "private_vs_shared_joy",
        type: "single",
        title: "Czy tym, co daje Ci radosc, chcesz sie dzielic?",
        options: [
          o("private", "Raczej chce zachowac to dla siebie", { independent: 1 }),
          o("share", "Chetnie dzielilabym sie tym z innymi", { communication: 1, relational: 1 }),
          o("dont_know", "Nie wiem jeszcze", { explorer: 1 }),
          o("depends", "Zalezy od formy", { strategic: 1 }),
        ],
      },
      {
        id: "safe_sharing_forms",
        type: "multi",
        title: "Jaka forma dzielenia sie bylaby dla Ciebie najbezpieczniejsza?",
        options: [
          o("text", "Tekst", { communication: 1, creative: 1 }),
          o("image", "Zdjecia lub obraz", { aesthetic: 1, creative: 1 }),
          o("video", "Wideo", { visibility: 2, communication: 1 }),
          o("one_to_one", "Rozmowy 1:1", { relational: 2 }),
          o("community", "Mala spolecznosc", { relational: 1, leadership: 1 }),
          o("product", "Produkt", { builder: 2, businessReadiness: 1 }),
          o("workshop", "Warsztat", { educational: 1, leadership: 1 }),
          o("consulting", "Konsultacje", { caring: 1, communication: 1 }),
          o("unknown", "Nie wiem"),
        ],
      },
    ],
  },
  joy_flow_checkpoint: {
    id: "joy_flow_checkpoint",
    order: 4,
    eyebrow: "Checkpoint 2",
    title: "Sygnal z tego etapu",
    subtitle:
      "Ten etap nie ma powiedziec Ci, co masz robic dalej. Ma tylko pokazac, po czym jest Ci bardziej zywo i bezpiecznie w sobie.",
    generated: "checkpoint",
    checkpointFor: "joy_flow",
    questions: [
      {
        id: "joy_flow_checkpoint_note",
        type: "textarea",
        title: "Jedna mysl na dzis",
        description: "Zapisz jedna rzecz, ktora chcesz zapamietac o swojej energii i radosci.",
        placeholder: "Np. ozywia mnie..., odcina mnie od siebie..., chce sprawdzac wiecej...",
        required: false,
        trackProgress: false,
      },
    ],
  },
  talents: {
    id: "talents",
    order: 5,
    eyebrow: "Etap 3",
    title: "Talenty i naturalna latwosc",
    subtitle:
      "Talent to nie zawsze powolanie. Czasem cos umiemy, ale nie chcemy tego robic codziennie. Dlatego sprawdzimy zarowno latwosc, jak i energie.",
    questions: [
      {
        id: "others_praise",
        type: "textarea",
        title: "Za co inni najczesciej Cie chwala?",
        description: "Za co ludzie prosza Cie o pomoc albo mowia: Ty to umiesz?",
      },
      {
        id: "talent_statements",
        type: "multi",
        title: "Ktore zdania brzmia jak Ty?",
        options: [
          o("sense_emotions", "Szybko wyczuwam, co ktos czuje", { relational: 2, caring: 1 }),
          o("name_unsaid", "Potrafie nazwac to, czego inni nie umieja nazwac", { communication: 2, analytical: 1 }),
          o("see_potential", "Widze potencjal w ludziach lub pomyslach", { strategic: 1, caring: 1, creative: 1 }),
          o("many_ideas", "Mam duzo pomyslow", { creative: 2, explorer: 1 }),
          o("simplify", "Umiem upraszczac skomplikowane rzeczy", { educational: 2, communication: 1 }),
          o("good_eye", "Mam dobre oko do estetyki", { aesthetic: 2 }),
          o("process_issue", "Widze, co nie dziala w procesie", { analytical: 2, organizational: 1 }),
          o("improve", "Lubie poprawiac i ulepszac", { builder: 1, strategic: 1 }),
          o("create_mood", "Umiem stworzyc atmosfere", { relational: 1, aesthetic: 1, caring: 1 }),
          o("motivate_people", "Potrafie zmotywowac innych", { leadership: 2, communication: 1 }),
          o("plan", "Lubie planowac", { strategic: 2, organizational: 1 }),
          o("trends", "Mam intuicje do trendow", { explorer: 1, aesthetic: 1, strategic: 1 }),
          o("listen_no_judge", "Umiem sluchac bez oceniania", { caring: 2, relational: 2 }),
          o("trust", "Latwo buduje zaufanie", { relational: 2, communication: 1 }),
          o("show_value", "Potrafie pokazywac wartosc", { businessReadiness: 1, communication: 1 }),
          o("teach", "Lubie uczyc innych", { educational: 2, communication: 1 }),
          o("write_well", "Dobrze pisze", { communication: 2, creative: 1 }),
          o("speak_well", "Dobrze mowie", { communication: 2, visibility: 1 }),
          o("practical", "Lubie dzialac praktycznie", { builder: 2 }),
        ],
      },
      {
        id: "talent_but_not_work",
        type: "textarea",
        title: "Czy jest cos, co umiesz, ale nie chcesz robic tego jako pracy?",
        description: "To wazne, bo nie kazdy talent powinien byc monetyzowany.",
      },
      {
        id: "confidence_in_talents",
        type: "rating",
        title: "Jak bardzo ufasz swoim talentom?",
        description: "1 - prawie wcale, 10 - bardzo mocno",
        min: 1,
        max: 10,
      },
      {
        id: "talent_energy_notes",
        type: "textarea",
        title: "Ktore z Twoich talentow daja Ci energie, a ktore raczej Cie mecza?",
        description: "Opisz to wlasnymi slowami.",
      },
    ],
  },
  emotions: {
    id: "emotions",
    order: 6,
    eyebrow: "Etap 4",
    title: "Emocje jako kompas",
    subtitle:
      "To, co nas frustruje albo porusza, czesto wskazuje na wartosci. Nie musi od razu oznaczac kierunku zawodowego - moze po prostu pokazywac, co jest dla Ciebie wazne.",
    questions: [
      {
        id: "emotions_support",
        type: "info",
        title: "To normalne, jesli to porusza",
        description:
          "Jesli przy tym etapie czujesz napiecie, smutek albo zlosc, nie znaczy to, ze robisz cos zle. Mozesz odpowiedziec krotko, zatrzymac sie albo wrocic do tych pytan pozniej.",
      },
      {
        id: "world_frustration",
        type: "textarea",
        title: "Co najbardziej frustruje Cie w swiecie, ludziach, pracy albo codziennosci?",
        description: "Nie oceniaj odpowiedzi. Napisz to szczerze.",
      },
      {
        id: "what_should_change",
        type: "textarea",
        title: "Gdybys mogla cos w tym zmienic, co by to bylo?",
      },
      {
        id: "problems_to_solve",
        type: "multi",
        title: "Jakie problemy innych ludzi naturalnie chcesz rozwiazywac?",
        options: [
          o("confidence", "Brak pewnosci siebie", { caring: 1, relational: 1 }),
          o("life_chaos", "Chaos w zyciu lub pracy", { organizational: 2, strategic: 1 }),
          o("emotions_named", "Trudnosc w nazwaniu emocji", { caring: 2, communication: 1 }),
          o("no_self_idea", "Brak pomyslu na siebie", { meaning: 2, caring: 1 }),
          o("low_self_worth", "Niska samoocena", { caring: 2 }),
          o("relations", "Problemy w relacjach", { relational: 2 }),
          o("no_beauty", "Brak estetyki, harmonii albo piekna", { aesthetic: 2 }),
          o("how_start", "Brak wiedzy jak zaczac", { educational: 2, builder: 1 }),
          o("overload", "Przeciazenie", { caring: 1, organizational: 1 }),
          o("loneliness", "Samotnosc", { relational: 2 }),
          o("no_courage", "Brak odwagi do dzialania", { leadership: 1, caring: 1 }),
          o("communication_hard", "Trudnosc w komunikacji", { communication: 2, relational: 1 }),
          o("no_organization", "Brak organizacji", { organizational: 2 }),
          o("habits", "Brak zdrowych nawykow", { builder: 1, caring: 1 }),
        ],
      },
      {
        id: "moved_to_tears",
        type: "textarea",
        title: "Co potrafi Cie mocno poruszyc?",
        description:
          "Moze pozytywnie albo negatywnie: czyjas przemiana, piekno, niesprawiedliwosc, bliskosc, wolnosc, odwaga, prawda, cierpienie, sukces...",
      },
      {
        id: "core_values",
        type: "multi",
        title: "Jakie wartosci najmocniej czujesz w swoich odpowiedziach?",
        options: [
          o("freedom", "Wolnosc", { freedom: 2 }),
          o("authenticity", "Autentycznosc", { meaning: 2 }),
          o("justice", "Sprawiedliwosc", { impact: 2 }),
          o("beauty", "Piekno", { aesthetic: 2 }),
          o("closeness", "Bliskosc", { relational: 2 }),
          o("growth", "Rozwoj", { explorer: 1, meaning: 1 }),
          o("peace", "Spokoj", { stability: 1 }),
          o("impact", "Wplyw", { impact: 2, leadership: 1 }),
          o("safety", "Bezpieczenstwo", { stability: 2 }),
          o("truth", "Prawda", { analytical: 1, meaning: 1 }),
          o("help", "Pomoc", { caring: 2 }),
        ],
      },
    ],
  },
  emotions_checkpoint: {
    id: "emotions_checkpoint",
    order: 7,
    eyebrow: "Checkpoint 3",
    title: "Sygnal z tego etapu",
    subtitle:
      "Po pytaniach o emocje nie potrzebujesz jeszcze rozwiazania. Wystarczy zobaczyc, co chce byc nazwane i czego nie trzeba juz dluzej ignorowac.",
    generated: "checkpoint",
    checkpointFor: "emotions",
    questions: [
      {
        id: "emotions_checkpoint_note",
        type: "textarea",
        title: "Jedna mysl na dzis",
        description: "Zapisz jedno zdanie, ktore chcesz zapamietac po tym etapie.",
        placeholder: "Np. coraz wyrazniej widze, ze wazne jest dla mnie...",
        required: false,
        trackProgress: false,
      },
    ],
  },
  work_style: {
    id: "work_style",
    order: 8,
    eyebrow: "Etap 5",
    title: "Styl zycia i pracy",
    subtitle:
      "Dobry kierunek to nie tylko temat. To tez forma pracy, tempo, ilosc ludzi, widocznosc i poziom ryzyka. Szukamy stylu, w ktorym mozesz oddychac, a nie tylko dzialac.",
    questions: [
      {
        id: "ideal_workday",
        type: "textarea",
        title: "Jak wyglada dzien pracy, ktory naprawde Ci sluzy?",
        description:
          "Nie idealny instagramowo. Realny. Taki, po ktorym czujesz: moglabym tak zyc.",
      },
      {
        id: "freedom_vs_stability",
        type: "rating",
        title: "Wolnosc czy stabilnosc?",
        description: "1 - bardzo potrzebuje stabilnosci, 10 - bardzo potrzebuje wolnosci",
        min: 1,
        max: 10,
      },
      {
        id: "solo_vs_people",
        type: "rating",
        title: "Jak bardzo chcesz pracowac z ludzmi?",
        description: "1 - glownie sama, 10 - bardzo duzo z ludzmi",
        min: 1,
        max: 10,
      },
      {
        id: "visibility_comfort",
        type: "single",
        title: "Jak czujesz sie z byciem widoczna?",
        options: [
          o("like_visible", "Lubie byc widoczna", { visibility: 3, communication: 1 }),
          o("want_resist", "Chce byc widoczna, ale mam opor", { visibility: 1 }),
          o("behind", "Wole dzialac za kulisami", { visibility: -2, independent: 1 }),
          o("depends", "Zalezy od tematu i formy", { strategic: 1 }),
          o("not_ready", "Jeszcze nie wiem albo nie chce tego teraz rozstrzygac", { explorer: 1 }),
        ],
      },
      {
        id: "preferred_pace",
        type: "single",
        title: "Jakie tempo rozwoju jest dla Ciebie najzdrowsze?",
        options: [
          o("slow", "Wolno, spokojnie, bez presji", { stability: 2 }),
          o("regular", "Regularnie, ale bez chaosu", { organizational: 1, stability: 1 }),
          o("dynamic", "Dynamicznie, lubie czuc ruch", { explorer: 1, businessReadiness: 1 }),
          o("waves", "Falami - intensywnie, potem odpoczynek", { creative: 1, freedom: 1 }),
        ],
      },
      {
        id: "hard_no_list",
        type: "multi",
        title: "Czego nie chcesz w swojej przyszlej pracy, projekcie albo biznesie?",
        options: [
          o("sales_pressure", "Ciaglej presji sprzedazy", { businessReadiness: -1 }),
          o("always_online", "Bycia caly czas online", { stability: 1 }),
          o("many_people", "Pracy z duza liczba ludzi", { independent: 1 }),
          o("monotony", "Monotonii", { explorer: 1, creative: 1 }),
          o("chaos", "Chaosu", { organizational: 1, stability: 1 }),
          o("fixed_hours", "Sztywnych godzin", { freedom: 2 }),
          o("instability", "Braku stabilnosci", { stability: 2 }),
          o("public_speaking", "Wystepowania publicznego", { visibility: -2 }),
          o("one_client", "Pracy sam na sam z klientem", { relational: -1 }),
          o("operations", "Pracy operacyjnej", { strategic: 1 }),
          o("responsibility", "Duzej odpowiedzialnosci za innych", { caring: -1 }),
          o("content_pressure", "Ciaglego tworzenia contentu", { visibility: -1, creative: -1 }),
        ],
      },
    ],
  },
  work_style_checkpoint: {
    id: "work_style_checkpoint",
    order: 9,
    eyebrow: "Checkpoint 4",
    title: "Sygnal z tego etapu",
    subtitle:
      "Ten etap pomaga oddzielic cudze wyobrazenia od tego, co naprawde sluzy Twojemu zyciu. Zobacz, jaki styl zaczyna wygladac na bardziej Twoj.",
    generated: "checkpoint",
    checkpointFor: "work_style",
    questions: [
      {
        id: "work_style_checkpoint_note",
        type: "textarea",
        title: "Jedna mysl na dzis",
        description: "Zapisz jedna rzecz, ktora chcesz chronic w swoim przyszlym sposobie dzialania.",
        placeholder: "Np. potrzebuje wiecej spokoju..., nie chce juz wracac do..., dobrze mi sluzy...",
        required: false,
        trackProgress: false,
      },
    ],
  },
  business: {
    id: "business",
    order: 10,
    eyebrow: "Etap 6",
    title: "Forma dzialania, pieniadze i gotowosc",
    subtitle:
      "Nie wszystko musi stac sie biznesem. Ten etap pomaga sprawdzic, czy chcesz cos testowac zawodowo, projektowo albo prywatnie - i w jakiej formie byloby to dla Ciebie najbezpieczniejsze.",
    questions: [
      {
        id: "business_support",
        type: "info",
        title: "To normalne, jesli nie chcesz tego jeszcze nazywac biznesem",
        description:
          "Mozesz myslec o tym jako o projekcie pobocznym, spokojnej pracy, malej usludze, tworczosci prywatnej albo czyms, co dopiero sprawdzasz. Nie potrzebujesz teraz jednej etykiety.",
      },
      {
        id: "business_feeling",
        type: "single",
        title: "Kiedy myslisz o zrobieniu czegos bardziej po swojemu, co czujesz najbardziej?",
        options: [
          o("excitement", "Ekscytacje", { businessReadiness: 2, explorer: 1 }),
          o("curiosity", "Ciekawosc", { businessReadiness: 1, explorer: 1 }),
          o("fear", "Lek"),
          o("pressure", "Presje"),
          o("resistance", "Opor"),
          o("mix", "Mieszanke wszystkiego", { explorer: 1 }),
          o("not_now", "Jeszcze nie chce tego rozstrzygac", { stability: 1 }),
        ],
      },
      {
        id: "why_business",
        type: "multi",
        title: "Dlaczego w ogole myslisz o czyms bardziej swoim?",
        options: [
          o("freedom", "Chce wiecej wolnosci", { freedom: 2, businessReadiness: 1 }),
          o("money", "Chce wiecej pieniedzy", { businessReadiness: 1 }),
          o("meaning", "Chce robic cos z sensem", { meaning: 2 }),
          o("own_way", "Chce tworzyc po swojemu", { creative: 1, freedom: 1 }),
          o("not_for_someone", "Nie chce pracowac dla kogos", { independent: 2, freedom: 1 }),
          o("impact", "Chce miec wplyw", { impact: 2 }),
          o("potential", "Chce sprawdzic swoj potencjal", { explorer: 2 }),
          o("bigger", "Chce zbudowac cos wiekszego", { leadership: 1, builder: 1 }),
          o("pull", "Nie wiem, po prostu mnie to ciagnie", { explorer: 1 }),
          o("soft_test", "Chce tylko lagodnie cos sprawdzic, bez presji", { stability: 1, explorer: 1 }),
        ],
      },
      {
        id: "preferred_next_form",
        type: "multi",
        title: "Jaka forma na ten moment brzmi najbezpieczniej do sprawdzenia?",
        options: [
          o("side_project", "Projekt poboczny po godzinach", { builder: 1, stability: 1 }),
          o("calm_job", "Spokojna praca bardziej zgodna ze mna", { stability: 2, meaning: 1 }),
          o("small_service", "Mala usluga albo rozmowy 1:1", { caring: 1, communication: 1, businessReadiness: 1 }),
          o("digital_product", "Maly produkt cyfrowy", { builder: 1, creative: 1, businessReadiness: 1 }),
          o("private_creativity", "Tworczosc prywatna bez monetyzacji na teraz", { creative: 1, meaning: 1, stability: 1 }),
          o("behind_scenes", "Rola za kulisami albo wsparcie innych", { strategic: 1, organizational: 1, independent: 1 }),
          o("not_sure_yet", "Nie wiem jeszcze i to jest w porzadku", { explorer: 1 }),
        ],
      },
      {
        id: "money_relationship",
        type: "multi",
        title: "Ktore zdania sa Ci najblizsze?",
        options: [
          o("earn_calm", "Chce dobrze zarabiac, ale nie kosztem zdrowia i spokoju", { stability: 1 }),
          o("work_if_meaning", "Jestem gotowa intensywnie pracowac, jesli widze sens", { businessReadiness: 2, meaning: 1 }),
          o("stability_first", "Najpierw chce stabilnosci, potem eksperymentow", { stability: 2 }),
          o("meaning_more", "Pieniadze sa wazne, ale sens jest wazniejszy", { meaning: 2 }),
          o("unknown_money", "Nie wiem jeszcze, jaka jest moja relacja z pieniedzmi", { explorer: 1 }),
        ],
      },
      {
        id: "experiment_readiness",
        type: "rating",
        title: "Jak bardzo jestes gotowa sprawdzic swoje pomysly w praktyce?",
        description: "1 - prawie wcale, 10 - bardzo mocno",
        min: 1,
        max: 10,
      },
      {
        id: "business_blockers",
        type: "multi",
        title: "Co moze Cie zatrzymywac?",
        options: [
          o("judgement", "Strach przed ocena", { visibility: -1 }),
          o("confidence", "Brak pewnosci siebie"),
          o("time", "Brak czasu"),
          o("idea", "Brak pomyslu"),
          o("start", "Nie wiem, od czego zaczac", { builder: -1 }),
          o("perfectionism", "Perfekcjonizm"),
          o("sales_fear", "Lek przed sprzedaza", { businessReadiness: -1 }),
          o("tired", "Zmeczenie"),
          o("too_many", "Za duzo opcji", { strategic: -1 }),
        ],
      },
    ],
  },
  profile_synthesis: {
    id: "profile_synthesis",
    order: 11,
    eyebrow: "Etap 7",
    title: "Synteza profilu",
    subtitle:
      "Na podstawie Twoich odpowiedzi aplikacja nie wyciaga ostatecznego wyniku, ale porzadkuje wzorce. To ma Ci pomoc zobaczyc siebie wyrazniej, a nie zamknac Cie w jednej definicji.",
    generated: "profile",
    questions: [
      {
        id: "profile_correction",
        type: "textarea",
        title: "Czy cos w tym profilu chcesz doprecyzowac?",
        description: "Mozesz dopisac, co wydaje sie trafne, nietrafne albo wazne.",
        required: false,
        trackProgress: false,
      },
    ],
  },
  suggested_paths: {
    id: "suggested_paths",
    order: 12,
    eyebrow: "Etap 8",
    title: "Potencjalne sciezki",
    subtitle:
      "Te sciezki sa hipotezami na podstawie Twoich odpowiedzi. Jedna sciezka nie wyklucza drugiej - chodzi o znalezienie kierunku, ktory warto teraz lagodnie sprawdzic.",
    generated: "paths",
    questions: [],
  },
  seven_day_experiment: {
    id: "seven_day_experiment",
    order: 13,
    eyebrow: "Etap 9",
    title: "Eksperyment 7-dniowy",
    subtitle:
      "Nie musisz zmieniac zycia w 7 dni. Masz tylko zebrac sygnaly z rzeczywistosci: energia, opor, ciekawosc, sens i realny odzew.",
    generated: "experiment",
    questions: [
      {
        id: "selected_path",
        type: "single",
        dynamicOptions: "suggestedPaths",
        title: "Ktora sciezke chcesz przetestowac jako pierwsza?",
        required: true,
      },
      {
        id: "experiment_feeling",
        type: "textarea",
        title: "Co czuje po przeczytaniu tego eksperymentu?",
        required: false,
        trackProgress: false,
      },
      {
        id: "easiest_first_step",
        type: "textarea",
        title: "Co jest dla mnie najlatwiejszym pierwszym krokiem?",
        required: false,
        trackProgress: false,
      },
      {
        id: "experiment_blocker",
        type: "textarea",
        title: "Co mnie blokuje?",
        required: false,
        trackProgress: false,
      },
    ],
  },
  decision_system: {
    id: "decision_system",
    order: 14,
    eyebrow: "Etap 10",
    title: "System decyzyjny",
    subtitle: "Ten etap tworzy osobisty filtr wyboru: po czym poznasz, ze cos naprawde do Ciebie pasuje.",
    questions: [
      {
        id: "mine_signals",
        type: "multi",
        title: "Po czym poznasz, ze cos jest naprawde Twoje?",
        options: [
          o("return", "Chce mi sie do tego wracac"),
          o("calm", "Czuje spokoj, nie tylko ekscytacje"),
          o("energy_after", "Mam energie po dzialaniu"),
          o("effect", "Widze realny efekt u innych"),
          o("myself", "Moge byc w tym soba"),
          o("no_pretend", "Nie musze udawac kogos innego"),
          o("sense", "Czuje sens"),
          o("curious_next", "Jestem ciekawa kolejnego kroku"),
          o("light_stress", "Czuje lekki stres, ale nie paraliz"),
          o("lifestyle_fit", "Pasuje to do mojego stylu zycia"),
        ],
      },
      {
        id: "excitement_pattern",
        type: "single",
        title: "Kiedy pojawia sie nowy pomysl, co zdarza sie czesciej?",
        options: [
          o("calm_step", "Czuje spokojna ciekawosc i chce zrobic maly krok"),
          o("big_then_drop", "Czuje wielka ekscytacje, ale szybko trace energie"),
          o("escape_new", "Uciekam w nowe pomysly, gdy cos robi sie trudne"),
          o("analyze", "Dlugo analizuje i nie zaczynam"),
          o("depends", "Roznie - zalezy od pomyslu"),
        ],
      },
      {
        id: "good_path_criteria",
        type: "multi",
        title: "Jakie warunki musi spelniac dobra droga?",
        options: [
          o("energy", "Daje mi energie"),
          o("meaning", "Ma sens"),
          o("earn", "Moze zarabiac"),
          o("helps", "Pomaga innym"),
          o("freedom", "Daje wolnosc"),
          o("stability", "Daje stabilnosc"),
          o("create", "Pozwala mi tworzyc"),
          o("lifestyle", "Pasuje do mojego stylu zycia"),
          o("growth", "Rozwija mnie"),
          o("not_overload", "Nie przeciaza mnie"),
        ],
      },
      {
        id: "personal_definition_notes",
        type: "textarea",
        title: "Dokoncz zdanie: dobra droga dla mnie to taka, ktora...",
        description: "Nie musi byc idealnie. To bedzie czesc Twojego koncowego promptu.",
      },
    ],
  },
  final_report: {
    id: "final_report",
    order: 15,
    eyebrow: "Etap 11",
    title: "Finalny raport i prompt do LLM",
    subtitle:
      "To nie jest ostateczna diagnoza. To lekkie podsumowanie tego, co juz o sobie widzisz, oraz osobna przestrzen do poglebienia tego w LLM, jesli zechcesz.",
    generated: "final",
    questions: [],
  },
};
